prod:
  image: vfarcic/books-service
  volumes:
    - /data/db:/data/db
  ports:
      - 8080:8080
  links:
    - db

db:
  image: mongo

downloadDeps:
  image: vfarcic/books-service-tests
  dockerfile: Dockerfile.test
  command: /source/download_dependencies.sh
  volumes:
    - /data/.ivy2:/root/.ivy2/cache
    - client:/source/client
    - src:/source/src
    - target:/source/target

feTestsWatch:
  image: vfarcic/books-service-tests
  dockerfile: Dockerfile.test
  stdin_open: true
  tty: true
  volumes:
    - /data/.ivy2:/root/.ivy2/cache
    - client:/source/client
    - src:/source/src
    - target:/source/target
    - package.json:/source/package.json
    - db:/data/db
  ports:
    - 8080:8080
  environment:
    - TEST_TYPE=watch-front